### PR TITLE
Add node.user to rvm group, make /usr/local/rvm recursively g+w

### LINKED ISSUE #24: Add ubuntu user to rvm group
Until switching away from rvm, need to add ubuntu user to rvm group before installing gems as root

### PR DESCRIPTION
**Pull request by mstine**
Fixes https://github.com/cloudfoundry-community/inception-server/issues/24

### CODE REVIEW

**Comment by drnic** [comment]
Mate, I'm going to merge in the chruby branch and discontinue rvm. Sorry
about that!

**Comment by drnic** [comment]
I mean, I'm really sorry - I'm doing it right now. I'm typing this whilst
doing a final test.

**Comment by mstine** [comment]
Well fiddlesticks. :-)

**Comment by drnic** [comment]
I KNOW!

**Pull request closed without merging**
